### ISSUE TITLE
Standby button not working properly

### ISSUE THREAD

**Issue by HyperDX** [HyperDX/TEF_ESP#1]
The problem has been there since I finished the modifications. all the buttons work without any problem, except the button responsible for switching the bands and the "standby" mode. The readings from the button are reversed. Pressing it (shorting D4 pin to ground) allows to use the tuner, while when the button is not pressed the tuner is in standby mode, and also after starting it shows the message about the calibration of the analogue meter.

I don't know if the problem is only with my case or with other modifications to the tuner in revision A

**Comment by HyperDX** [comment]
For the test I changed the "if" conditions when checking the button press status and it looks like the problem has been solved in my case. If in your case this problem occurs, please change the lines given in the commit from HIGH to LOW, unfortunately until I solve the hardware problem (if there is one) this solution seems to be the only one.

**Comment by zygmund2000** [comment]
Hi, at the moment with reversed stb pin tuner is not usable and always enter to menu :(

**Comment by HyperDX** [comment]
> Hi, at the moment with reversed stb pin tuner is not usable and always enter to menu :(

Fixed: https://github.com/HyperDX/TEF_ESP/releases/tag/v1.21.3
Dziękuję!

**Comment by zygmund2000** [comment]
Okej, that's better ;)
