### ISSUE TITLE
Precompiled version missing

### ISSUE THREAD

**Issue by andimik** [HyperDX/TEF_ESP#2]
in https://github.com/HyperDX/TEF_ESP/releases/tag/v1.21.3 I read that the precompiled version will just take a few days, but I cannot find it.

**Comment by HyperDX** [comment]
Sorry I totally forgot about that and when I wanted to make a binary file my ESP32 just burned so I had to replace it. I will provide compiled files soon.

**Comment by HyperDX** [comment]
Done.
See: [Release v1.21.3](https://github.com/HyperDX/TEF_ESP/releases/tag/v1.21.3)

**Comment by andimik** [comment]
Thanks!

**Comment by andimik** [comment]
I am sorry to tell you that this 1.21.3 does not work properly.

On my "Dutch" TEF v1 there is a message `Tuner: !NONE!` (which you can hardly read). So back to 1.15 from Sjef.
On my Chinese silver radio (2 knobs on the right) it boots into the well-known menu "PRESS MENU" and I cannot leave that. So back to 1.21 from Noobish.

**Comment by HyperDX** [comment]
Don't use TEF_ESP with Chinese tuners. I recommend using TEF6686-remastered instead, It enters you to MENU because here we have inverted PWR button to get this working...
